### ISSUE TITLE
HTML comments

### ISSUE THREAD

**Issue by jericahuang** [adnantg/prj-rev-bwfs-tea-cozy#1]
Something great about the way Github displays your code for you is it highlights errors in red. You see errors on lines with comments because there should only be two hyphens in the start! A quick fix to make.
`<!-- -->`

https://www.w3schools.com/html/html_comments.asp

**Comment by adnantg** [comment]
Thanks for pointing this out. I totally messed up the commenting syntax. Corrected in the latest commit.
